/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 8;
  /** RegularExpression Id. */
  int SIGN = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"  \\n\"",
    "\"\\r\"",
    "\" \\r\"",
    "\"\\r\\n\"",
    "\" \\r\\n\"",
    "<EOL>",
    "<SIGN>",
    "<NUMBER>",
  };

}
